title: Homepage
email: your-email@example.com
description: Tucker's cool website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com